src/ReservoirComputing.jl
src/esn_input_layers.jl
test/fixed_layers/test_esn_input_layers.jl

This is implementation of the input layer for the hybrid echo state network. It is assumed that the vector of inputs is such that the raw states are followed by the inputs of the model in order. The user specifies what the expected number of inputs are for the model, and some gamma for what percent of  the connections are made between the raw inputs and the reservoir nodes exclusively, while the rest are connected to the reservoir nodes and model inputs. No one reservoir node is connected to more than once. What remains is to allow the prior knowledge to be specified as an argument into an ESN model, and do the same for the output layer as what was done for the input layer

Hybrid esn input layer

---

Project.toml
src/ReservoirComputing.jl
src/esn_input_layers.jl
src/hesn.jl
test/constructors/test_hesn_constructors.jl
test/fixed_layers/test_esn_input_layers.jl
test/runtests.jl

Here's my implementation of the constructor for the HESN. One of the fields is a prior model function that generates data from a provided model of the form written below as well as the u0, tspan and tsteps to saveat. Wanted to make it so that any kind of differential equation can be accepted and generated given the user configures prior_model_data_generator to his problem:
```julia
function lorenz(du,u,p,t)
p = [10.0,28.0,8/3]
du[1] = p[1]*(u[2]-u[1])
du[2] = u[1]*(p[2]-u[3]) - u[2]
du[3] = u[1]*u[2] - p[3]*u[3]
end
function prior_model_data_generator(u0, tspan, tsteps, model = lorenz)
prob = ODEProblem(lorenz, u0, tspan) 
sol = Array(solve(prob, saveat = tsteps))
return sol
end
```
The rest of the added fields i.e physics_model_data, u0, tspan, and datasize are used for training and …

HESN-Constructor

---

Project.toml
src/ReservoirComputing.jl
src/echostatenetwork.jl
test/extras/test_extended_states.jl
test/runtests.jl
test/training/test_esnfitted.jl

This adds a ```ESNfitted``` function following the indications discussed in #92

Added ESNfitted function

---

.JuliaFormatter.toml
docs/pages.jl
docs/src/esn_tutorials/change_layers.md
src/ReservoirComputing.jl
src/esn/echostatenetwork.jl
src/esn/esn_input_layers.jl
src/esn/esn_reservoir_drivers.jl
src/esn/esn_reservoirs.jl
src/reca/reca_input_encodings.jl
src/states.jl
src/train/linear_regression.jl
test/esn/test_drivers.jl
test/esn/test_train.jl
test/runtests.jl

Let CI run to completion since I had to tweak a few things to get formatter to not error.

reapply formatter

---

README.md
docs/src/esn_tutorials/change_layers.md
src/ReservoirComputing.jl
src/esn/deepesn.jl
src/esn/esn.jl

Small docstring fixes

---

docs/src/api/inits.md
src/ReservoirComputing.jl
src/esn/esn_inits.jl
test/esn/test_inits.jl

Added low sparsity init

---

Project.toml
docs/src/api/states.md
src/ReservoirComputing.jl
src/states.jl
test/test_states.jl

Closes #255.
~Currently missing docstrings.~
Added docstrings.
Currently the states are subtyped under nonlinear algos, but this should change in the future when #191 is addressed

Adding PartialSquare

---

docs/src/api/states.md
src/ReservoirComputing.jl
src/states.jl
test/test_states.jl

closes #168. This also will need minor changes when #191 is addressed

Added ExtendedSquare

---

Project.toml
docs/src/api/inits.md
src/ReservoirComputing.jl
src/esn/esn_inits.jl
test/esn/test_inits.jl

added double_cycle initializer

---

src/esn/esn_inits.jl

Addressing type conversion in inits

---

docs/Project.toml
src/esn/esn_inits.jl

chore: up DifferentialEquations version in docs, format

---

docs/src/api/inits.md
src/ReservoirComputing.jl
src/esn/esn_inits.jl
test/esn/test_inits.jl

feat: add weighted_minimal initializer

---

src/esn/esn_inits.jl
src/esn/inits_components.jl

feat: added regular sample

---

docs/src/api/inits.md

docs: group similar inits

---

Project.toml
docs/src/api/inits.md
src/ReservoirComputing.jl
src/esn/esn_inits.jl
src/esn/inits_components.jl
test/esn/test_inits.jl

Generalize `double_cycle` to use the actual cycle as defined in `simple_cycle`. Additionally add a component `reverse_simple_cycle!` to simplify building similar initializers.

feat(inits): add `true_double_cycle` reservoir initializer

---

src/esn/esn_inits.jl
src/esn/inits_components.jl

feat: add uniform dimension check to reservoir inits

---

.JuliaFormatter.toml
docs/make.jl
src/esn/deepesn.jl
src/esn/esn.jl
src/esn/esn_inits.jl
src/esn/esn_predict.jl
src/esn/esn_reservoir_drivers.jl
src/esn/hybridesn.jl
src/esn/inits_components.jl
src/predict.jl
src/reca/reca.jl
src/reca/reca_input_encodings.jl
src/states.jl
test/esn/deepesn.jl
test/esn/test_drivers.jl
test/esn/test_hybrid.jl
test/esn/test_inits.jl
test/esn/test_train.jl
test/qa.jl
test/reca/test_predictive.jl
test/test_states.jl

style: comply with sciml style

---

docs/src/api/inits.md
docs/src/refs.bib
src/ReservoirComputing.jl
src/esn/esn_inits.jl
test/esn/test_inits.jl

Adds the initializer introduced in Ma, Haochun, et al. "Efficient forecasting of chaotic systems with block-diagonal and binary reservoir computing." Chaos: An Interdisciplinary Journal of Nonlinear Science 33.6 (2023).

feat: add block_diagonal initializer

---

src/esn/esn_inits.jl

feat: increase specificity for scaled_rand init

---

src/esn/esn_inits.jl

Fix 30 spelling errors throughout the codebase where 'lenght' was misspelled as 'length'.
All instances were in documentation and comments, no code functionality affected.

Fix spelling errors: lenght -> length
